[AUTH]
admin_password = 123

[API]
base_url = http://127.0.0.1:8000/api/v1/
;base_url =  http://192.168.0.194:443/api/v1/

[FACE_RECOGNITION]
detection_size = 640
similarity_threshold = 40
check_interval = 10

[CAMERA]
width = 640
height = 480
fps = 30

[RECORDING]
enabled = true
fps = 20
format = XVID

[FACE_MONITORING]
# Face Detection - odam borligini tekshirish (YOLO)
detection_interval = 5
detection_max_fail = 3

# Face Identification - yuzni tanib olish (InsightFace)
identification_interval = 10
identification_max_fail = 3

# Warning - ogohlantirish
warning_timeout = 30
