# Form implementation generated from reading ui file 'ui/main.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        MainWindow.resize(1365, 858)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.stack = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stack.setAutoFillBackground(False)
        self.stack.setStyleSheet("QStackedWidget#stack {\n"
"    background-image: url(\"resources/images/face_fon.jpg\");\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    background-origin: content;\n"
"    background-size: cover;\n"
"}")
        self.stack.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.stack.setObjectName("stack")
        self.page_main = QtWidgets.QWidget()
        self.page_main.setStyleSheet("")
        self.page_main.setObjectName("page_main")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.page_main)
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_6.addItem(spacerItem, 0, 1, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_2 = QtWidgets.QLabel(parent=self.page_main)
        self.label_2.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("Segoe UI,Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_2.setStyleSheet("QLabel {\n"
"    color: #2c3e50;\n"
"    font-size: 26px;\n"
"    font-weight: bold;\n"
"    font-family: \"Segoe UI\", \"Arial\";\n"
"}")
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_7.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 180, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout_7.addItem(spacerItem1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_logo_2 = QtWidgets.QLabel(parent=self.page_main)
        self.label_logo_2.setText("")
        self.label_logo_2.setPixmap(QtGui.QPixmap("resources/images/Logo.png"))
        self.label_logo_2.setScaledContents(False)
        self.label_logo_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_logo_2.setObjectName("label_logo_2")
        self.verticalLayout_6.addWidget(self.label_logo_2)
        self.label_6 = QtWidgets.QLabel(parent=self.page_main)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(24)
        self.label_6.setFont(font)
        self.label_6.setText("")
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.combo_choose_test = QtWidgets.QComboBox(parent=self.page_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_choose_test.sizePolicy().hasHeightForWidth())
        self.combo_choose_test.setSizePolicy(sizePolicy)
        self.combo_choose_test.setMinimumSize(QtCore.QSize(500, 0))
        self.combo_choose_test.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        self.combo_choose_test.setFont(font)
        self.combo_choose_test.setStyleSheet("QComboBox {\n"
"    border: 2px solid #8f8f91;\n"
"    border-radius: 8px;\n"
"    padding: 6px 30px 6px 10px;\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                                stop:0 #f0f0f0, stop:1 #dcdcdc);\n"
"    color: #333;\n"
"    font-size: 16px;\n"
"    font-family: Segoe UI;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 2px solid #2980b9;\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                                stop:0 #e0f7fa, stop:1 #b2ebf2);\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 25px;\n"
"    border-left: 1px solid #888;\n"
"    background: #ccc;\n"
"    border-top-right-radius: 8px;\n"
"    border-bottom-right-radius: 8px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(resources/images/arrow-down.png);\n"
"    width: 12px;\n"
"    height: 12px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border: 1px solid #888;\n"
"    selection-background-color: #2980b9;\n"
"    selection-color: white;\n"
"    background: white;\n"
"    font-size: 14px;\n"
"    font-family: Segoe UI;\n"
"}")
        self.combo_choose_test.setCurrentText("")
        self.combo_choose_test.setObjectName("combo_choose_test")
        self.verticalLayout_6.addWidget(self.combo_choose_test)
        spacerItem2 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.verticalLayout_6.addItem(spacerItem2)
        self.btn_next_page = QtWidgets.QPushButton(parent=self.page_main)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_next_page.setFont(font)
        self.btn_next_page.setStyleSheet("QPushButton {\n"
"    background-color: #2ecc71;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 8px 16px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    font-family: \"Segoe UI\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A8CCB3;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1c6ea4;\n"
"    padding-left: 10px;\n"
"    padding-top: 10px;\n"
"}\n"
"")
        self.btn_next_page.setDefault(True)
        self.btn_next_page.setFlat(False)
        self.btn_next_page.setObjectName("btn_next_page")
        self.verticalLayout_6.addWidget(self.btn_next_page)
        self.label_tests = QtWidgets.QLabel(parent=self.page_main)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.label_tests.setFont(font)
        self.label_tests.setText("")
        self.label_tests.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_tests.setObjectName("label_tests")
        self.verticalLayout_6.addWidget(self.label_tests)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        spacerItem3 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.label_3 = QtWidgets.QLabel(parent=self.page_main)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("resources/images/ap-hero.svg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.gridLayout_6.addLayout(self.verticalLayout_7, 1, 1, 2, 1)
        spacerItem4 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_6.addItem(spacerItem4, 2, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(108, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_6.addItem(spacerItem5, 2, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 48, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_6.addItem(spacerItem6, 3, 1, 1, 1)
        self.stack.addWidget(self.page_main)
        self.page_home = QtWidgets.QWidget()
        self.page_home.setObjectName("page_home")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_home)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem7 = QtWidgets.QSpacerItem(99, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_5.addItem(spacerItem7, 1, 4, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_5.addItem(spacerItem8, 1, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 63, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        self.gridLayout_5.addItem(spacerItem9, 0, 3, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 62, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        self.gridLayout_5.addItem(spacerItem10, 2, 3, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_org = QtWidgets.QLabel(parent=self.page_home)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_org.setFont(font)
        self.label_org.setMouseTracking(True)
        self.label_org.setStyleSheet("QLabel {\n"
"    color: #2c3e50;\n"
"    font-size: 36px;\n"
"    font-weight: bold;\n"
"}")
        self.label_org.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_org.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_org.setScaledContents(True)
        self.label_org.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_org.setWordWrap(False)
        self.label_org.setObjectName("label_org")
        self.verticalLayout_4.addWidget(self.label_org)
        spacerItem11 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        self.verticalLayout_4.addItem(spacerItem11)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_face = QtWidgets.QLabel(parent=self.page_home)
        self.label_face.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_face.sizePolicy().hasHeightForWidth())
        self.label_face.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.label_face.setFont(font)
        self.label_face.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_face.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.label_face.setText("")
        self.label_face.setPixmap(QtGui.QPixmap("resources/images/img1.jpg"))
        self.label_face.setScaledContents(True)
        self.label_face.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_face.setObjectName("label_face")
        self.horizontalLayout_2.addWidget(self.label_face)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem12)
        self.label_9 = QtWidgets.QLabel(parent=self.page_home)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMaximumSize(QtCore.QSize(600, 500))
        self.label_9.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("resources/images/id.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.label_response = QtWidgets.QLabel(parent=self.page_home)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_response.setFont(font)
        self.label_response.setText("")
        self.label_response.setScaledContents(True)
        self.label_response.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_response.setObjectName("label_response")
        self.verticalLayout_4.addWidget(self.label_response)
        self.gridLayout_5.addLayout(self.verticalLayout_4, 1, 1, 1, 3)
        self.stack.addWidget(self.page_home)
        self.page_pinfl = QtWidgets.QWidget()
        self.page_pinfl.setObjectName("page_pinfl")
        self.gridLayout = QtWidgets.QGridLayout(self.page_pinfl)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem13 = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem13, 0, 1, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(115, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem14, 1, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(parent=self.page_pinfl)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    color: #1e40af;\n"
"    font-size: 42px;\n"
"    font-weight: bold;\n"
"    font-family: \"Segoe UI\", \"Arial\";\n"
"    padding: 20px;\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 rgba(59, 130, 246, 0.1), stop:0.5 rgba(59, 130, 246, 0.2), stop:1 rgba(59, 130, 246, 0.1));\n"
"    border-radius: 12px;\n"
"}")
        self.label.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        spacerItem15 = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout_5.addItem(spacerItem15)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_10 = QtWidgets.QLabel(parent=self.page_pinfl)
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_3.addWidget(self.label_10)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.input_pinfl = QtWidgets.QLineEdit(parent=self.page_pinfl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_pinfl.sizePolicy().hasHeightForWidth())
        self.input_pinfl.setSizePolicy(sizePolicy)
        self.input_pinfl.setMinimumSize(QtCore.QSize(320, 56))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.input_pinfl.setFont(font)
        self.input_pinfl.setTabletTracking(False)
        self.input_pinfl.setStyleSheet("QLineEdit {\n"
"    font-size: 36px;\n"
"    font-weight: 600;\n"
"    padding: 12px 16px;\n"
"    letter-spacing: 4px;\n"
"    background: #ffffff;\n"
"    border: none;\n"
"    border-bottom: 3px solid #3b82f6;\n"
"    border-radius: 4px 4px 0 0;\n"
"    color: #1a1a2e;\n"
"    selection-background-color: #3b82f6;\n"
"    selection-color: #ffffff;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    background: #f8fafc;\n"
"    border-bottom: 3px solid #1d4ed8;\n"
"    color: #0f172a;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background: #f1f5f9;\n"
"}")
        self.input_pinfl.setInputMask("")
        self.input_pinfl.setText("")
        self.input_pinfl.setMaxLength(14)
        self.input_pinfl.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.input_pinfl.setDragEnabled(True)
        self.input_pinfl.setPlaceholderText("14 xonali PINFL raqamingiz")
        self.input_pinfl.setObjectName("input_pinfl")
        self.verticalLayout.addWidget(self.input_pinfl)
        self.btn_check_im = QtWidgets.QPushButton(parent=self.page_pinfl)
        self.btn_check_im.setMinimumSize(QtCore.QSize(0, 55))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_check_im.setFont(font)
        self.btn_check_im.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 8px 16px;\n"
"    font-size: 24px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2980b9;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1c6ea4;\n"
"    padding-left: 10px;\n"
"    padding-top: 10px;\n"
"}\n"
"")
        icon = QtGui.QIcon.fromTheme("check")
        self.btn_check_im.setIcon(icon)
        self.btn_check_im.setAutoDefault(True)
        self.btn_check_im.setDefault(True)
        self.btn_check_im.setFlat(False)
        self.btn_check_im.setObjectName("btn_check_im")
        self.verticalLayout.addWidget(self.btn_check_im)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.label_5 = QtWidgets.QLabel(parent=self.page_pinfl)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem16)
        self.label_4 = QtWidgets.QLabel(parent=self.page_pinfl)
        self.label_4.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("resources/images/ps.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout_5, 1, 1, 1, 2)
        spacerItem17 = QtWidgets.QSpacerItem(114, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem17, 1, 3, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem18, 2, 2, 1, 1)
        self.stack.addWidget(self.page_pinfl)
        self.page_face = QtWidgets.QWidget()
        self.page_face.setObjectName("page_face")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_face)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_face_check = QtWidgets.QLabel(parent=self.page_face)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_face_check.sizePolicy().hasHeightForWidth())
        self.label_face_check.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_face_check.setFont(font)
        self.label_face_check.setStyleSheet("QLabel {\n"
"    color: #2c3e50;\n"
"    font-size: 36px;\n"
"    font-weight: bold;\n"
"    font-family: \"Segoe UI\", \"Arial\";\n"
"}")
        self.label_face_check.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_face_check.setObjectName("label_face_check")
        self.verticalLayout_11.addWidget(self.label_face_check)
        spacerItem19 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_11.addItem(spacerItem19)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_13 = QtWidgets.QLabel(parent=self.page_face)
        self.label_13.setText("")
        self.label_13.setScaledContents(True)
        self.label_13.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_4.addWidget(self.label_13)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_video_box = QtWidgets.QLabel(parent=self.page_face)
        self.label_video_box.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_video_box.sizePolicy().hasHeightForWidth())
        self.label_video_box.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.label_video_box.setFont(font)
        self.label_video_box.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.label_video_box.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.label_video_box.setText("")
        self.label_video_box.setPixmap(QtGui.QPixmap("resources/images/img1.jpg"))
        self.label_video_box.setScaledContents(True)
        self.label_video_box.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_video_box.setObjectName("label_video_box")
        self.verticalLayout_2.addWidget(self.label_video_box)
        self.label_result_face_candidate = QtWidgets.QLabel(parent=self.page_face)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_result_face_candidate.setFont(font)
        self.label_result_face_candidate.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_result_face_candidate.setText("")
        self.label_result_face_candidate.setScaledContents(True)
        self.label_result_face_candidate.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_result_face_candidate.setObjectName("label_result_face_candidate")
        self.verticalLayout_2.addWidget(self.label_result_face_candidate)
        self.btn_candidate_next = QtWidgets.QPushButton(parent=self.page_face)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_candidate_next.sizePolicy().hasHeightForWidth())
        self.btn_candidate_next.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.btn_candidate_next.setFont(font)
        self.btn_candidate_next.setStyleSheet("QPushButton {\n"
"    background-color: #318CE7;\n"
"    color: white;\n"
"    border: 1px solid blue;\n"
"    border-radius: 8px;\n"
"    padding: 8px 16px;\n"
"    font-size: 24px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2980b9;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1c6ea4;\n"
"    padding-left: 10px;\n"
"    padding-top: 10px;\n"
"}\n"
"")
        self.btn_candidate_next.setAutoDefault(True)
        self.btn_candidate_next.setDefault(True)
        self.btn_candidate_next.setObjectName("btn_candidate_next")
        self.verticalLayout_2.addWidget(self.btn_candidate_next)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.label_14 = QtWidgets.QLabel(parent=self.page_face)
        self.label_14.setText("")
        self.label_14.setScaledContents(True)
        self.label_14.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_4.addWidget(self.label_14)
        self.verticalLayout_11.addLayout(self.horizontalLayout_4)
        self.gridLayout_3.addLayout(self.verticalLayout_11, 1, 1, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_3.addItem(spacerItem20, 1, 0, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_3.addItem(spacerItem21, 1, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(parent=self.page_face)
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 2, 1, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_3.addItem(spacerItem22, 0, 1, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_3.addItem(spacerItem23, 3, 1, 1, 1)
        self.stack.addWidget(self.page_face)
        self.page_note = QtWidgets.QWidget()
        self.page_note.setObjectName("page_note")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.page_note)
        self.gridLayout_8.setObjectName("gridLayout_8")
        spacerItem24 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.gridLayout_8.addItem(spacerItem24, 0, 1, 1, 1)
        spacerItem25 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_8.addItem(spacerItem25, 1, 0, 1, 1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_not_title = QtWidgets.QLabel(parent=self.page_note)
        font = QtGui.QFont()
        font.setPointSize(32)
        self.label_not_title.setFont(font)
        self.label_not_title.setStyleSheet("color: rgb(255, 55, 75);")
        self.label_not_title.setScaledContents(True)
        self.label_not_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_not_title.setObjectName("label_not_title")
        self.verticalLayout_9.addWidget(self.label_not_title)
        self.scrollArea = QtWidgets.QScrollArea(parent=self.page_note)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 98, 28))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.scrollAreaWidgetContents.setFont(font)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.label_warning_text = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_warning_text.setGeometry(QtCore.QRect(80, 20, 1041, 551))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.label_warning_text.setFont(font)
        self.label_warning_text.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.label_warning_text.setScaledContents(False)
        self.label_warning_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignJustify|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_warning_text.setWordWrap(True)
        self.label_warning_text.setObjectName("label_warning_text")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_9.addWidget(self.scrollArea)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_12 = QtWidgets.QLabel(parent=self.page_note)
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_5.addWidget(self.label_12)
        self.btn_start_test = QtWidgets.QPushButton(parent=self.page_note)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_start_test.sizePolicy().hasHeightForWidth())
        self.btn_start_test.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.btn_start_test.setFont(font)
        self.btn_start_test.setStyleSheet("QPushButton {\n"
"    background-color: #318CE7;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 8px 16px;\n"
"    font-size: 22px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2980b9;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1c6ea4;\n"
"    padding-left: 10px;\n"
"    padding-top: 10px;\n"
"}\n"
"")
        self.btn_start_test.setDefault(True)
        self.btn_start_test.setObjectName("btn_start_test")
        self.horizontalLayout_5.addWidget(self.btn_start_test)
        self.label_15 = QtWidgets.QLabel(parent=self.page_note)
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_5.addWidget(self.label_15)
        self.verticalLayout_9.addLayout(self.horizontalLayout_5)
        self.gridLayout_8.addLayout(self.verticalLayout_9, 1, 1, 2, 1)
        spacerItem26 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_8.addItem(spacerItem26, 2, 2, 1, 1)
        spacerItem27 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.gridLayout_8.addItem(spacerItem27, 3, 1, 1, 1)
        self.stack.addWidget(self.page_note)
        self.page_test = QtWidgets.QWidget()
        self.page_test.setObjectName("page_test")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_test)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.layout_test = QtWidgets.QVBoxLayout()
        self.layout_test.setObjectName("layout_test")
        self.gridLayout_2.addLayout(self.layout_test, 0, 0, 1, 1)
        self.stack.addWidget(self.page_test)
        self.page_no_internet = QtWidgets.QWidget()
        self.page_no_internet.setObjectName("page_no_internet")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.page_no_internet)
        self.gridLayout_7.setObjectName("gridLayout_7")
        spacerItem28 = QtWidgets.QSpacerItem(20, 55, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_7.addItem(spacerItem28, 0, 1, 1, 1)
        spacerItem29 = QtWidgets.QSpacerItem(174, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_7.addItem(spacerItem29, 1, 0, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_8 = QtWidgets.QLabel(parent=self.page_no_internet)
        font = QtGui.QFont()
        font.setPointSize(32)
        self.label_8.setFont(font)
        self.label_8.setScaledContents(True)
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_8.addWidget(self.label_8)
        spacerItem30 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_8.addItem(spacerItem30)
        self.label_7 = QtWidgets.QLabel(parent=self.page_no_internet)
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("resources/images/no-wifi.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_8.addWidget(self.label_7)
        self.gridLayout_7.addLayout(self.verticalLayout_8, 1, 1, 1, 1)
        spacerItem31 = QtWidgets.QSpacerItem(174, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_7.addItem(spacerItem31, 1, 2, 1, 1)
        spacerItem32 = QtWidgets.QSpacerItem(20, 78, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_7.addItem(spacerItem32, 2, 1, 1, 1)
        self.stack.addWidget(self.page_no_internet)
        self.gridLayout_4.addWidget(self.stack, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stack.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Safe Browser"))
        self.label_2.setText(_translate("MainWindow", "BILIM VA MALAKALARNI BAHOLASH AGENTLIGI\n"
" PROCTORING TIZIMI"))
        self.btn_next_page.setText(_translate("MainWindow", "Keyingi"))
        self.label_org.setText(_translate("MainWindow", "Ruxsat etilgan xodimlarni tizimga kirishi uchun \n"
"FACE ID tekshiruvi"))
        self.label.setText(_translate("MainWindow", "Hurmatli talabgor(test topshiruvchi) JSHSHIR nomerizni kiriting"))
        self.btn_check_im.setText(_translate("MainWindow", "Tizimga kirish"))
        self.label_face_check.setText(_translate("MainWindow", "Talabgorni yuz tekshiruvidan o\'tkazish oynasi"))
        self.btn_candidate_next.setText(_translate("MainWindow", "Davom etish"))
        self.label_not_title.setText(_translate("MainWindow", "Nomzodlarga eslatma!"))
        self.label_warning_text.setText(_translate("MainWindow", "<html><head/><body><p>Arrange for stable Internet connectivity.</p><p>Giving examination on Laptop or Desktop is highly recommended.</p><p>Make sure mobile/laptop is fully charged. Power bank for mobile or</p><p>UPS/Inverter for laptop/desktop should be arranged for uninterrupted</p><p>power supply.</p><p>Students should have sufficient data in Fair Usage Policy (FUP) / Internet</p><p>plan with sufficient data pack of internet service provider.</p><p>Login to the portal 10 min before the online examination start time.</p><p>Close all browsers/tabs before starting the online examination.</p><p>Once the exam starts, do not switch to any other window/tab. On doing so,</p><p>your attempt may be considered as malpractice and your exam may get terminated.</p><p>Do Not Pickup/Receive the Call during the exam if you are giving the exam</p><p>on mobile. This also will be treated as changing the window.</p><p>To avoid unwanted pop-ups, use of Ad Blocker is recommended.</p><p>Clear browser cache memory on mobile and laptops. Clear browsing</p><p>history and also delete temp files.</p></body></html>"))
        self.btn_start_test.setText(_translate("MainWindow", "Testni boshlash"))
        self.label_8.setText(_translate("MainWindow", "Internet bilan aloqa yo\'q!"))
